In [1]:
import numpy as np


In [51]:
a = np.array([1,10,100]) * np.ones(shape=(2,3))
b = 2 * np.array([1,10,100])* np.ones(shape=(2,3))
c = 3 * np.array([1,10,100])* np.ones(shape=(2,3))

n = np.array([a.T,b.T,c.T])

In [52]:
n = n.transpose(1,0,2)

In [53]:
n

array([[[  1.,   1.],
        [  2.,   2.],
        [  3.,   3.]],

       [[ 10.,  10.],
        [ 20.,  20.],
        [ 30.,  30.]],

       [[100., 100.],
        [200., 200.],
        [300., 300.]]])

In [54]:
np.mean(n, axis=0)

array([[ 37.,  37.],
       [ 74.,  74.],
       [111., 111.]])

In [50]:
np.mean(2*np.array([1,10,100]))

74.0

In [64]:
np.std(2*np.array([1,10,100]))

89.39798655450804

In [55]:
mu = np.mean(n, axis=0)
sigma = np.std(n, axis=0)

In [57]:
(n - mu) 

array([[[ -36.,  -36.],
        [ -72.,  -72.],
        [-108., -108.]],

       [[ -27.,  -27.],
        [ -54.,  -54.],
        [ -81.,  -81.]],

       [[  63.,   63.],
        [ 126.,  126.],
        [ 189.,  189.]]])

In [59]:
sigma

array([[ 44.69899328,  44.69899328],
       [ 89.39798655,  89.39798655],
       [134.09697983, 134.09697983]])

In [65]:
72/89.397

0.8053961542333635

In [66]:
36 / 44.698

0.8054051635419929